hyperium/h2

Cargo.toml

tokio-io 0.1.3 has been published so the "replace" for tokio-io 0.1.2
is no longer useful and it breaks the build with some (but apparently
not all) versions of Cargo.
Update the dependency to tokio-io 0.1.3 since that is the version
that's what's been verified to work.

Fix build by upgrading tokio-io dependency to tokio-io 0.1.3.

---

Cargo.toml
examples/akamai.rs

With this change, h2 can build and run without any manual configuration
steps for -msvc targets. Previously manual installation of OpenSSL
libraries was required.

Switch Akamai example from rust-openssl to Rustls.

---

examples/server.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/store.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs

Because, you might think that each linked list has exclusive access to
the next pointer, but then there is an edge case that proves otherwise.
Also, debugging this kind of thing is annoying.

Do not reuse next ptr for multiple linked lists

---

Cargo.toml
examples/akamai.rs

Use a temporary private fork of tokio-rustls that uses Rustls 0.12
until tokio-rustls 0.4 is released.
This upgrades, among other things, *ring* to 0.12, which will ensure
that it still builds in the Rust 1.20 release coming this week even if
backward-compatibility-breaking changes to rustc aren't fixed before
the release.

Update TLS-related dependencies.

---

src/frame/headers.rs
src/proto/streams/recv.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs

If a content-length header is provided, the value should match the sum
of all data frame lengths. If there is a mismatch, then the stream is
reset.

Validate received content-length header

---

src/client.rs

This type constraint shouldn't be necessary, and is cumbersome.

Remove AsyncRead + AsyncWrite constraint from h2::Client

---

src/codec/error.rs
src/proto/streams/flow_control.rs
src/proto/streams/recv.rs
src/proto/streams/streams.rs
tests/flow_control.rs

Initial work to aggregate window update frames. Arbitrarily chose a 50% ratio, as that was the default in netty, and the non-customizable ratio in nghttp2.
Closes #39

aggregate WINDOW_UPDATE frames until change is over 50% available

---

tests/flow_control.rs
tests/support/src/frames.rs
tests/support/src/lib.rs
tests/support/src/mock.rs
tests/support/src/prelude.rs

- Add `support::frames` builders, to ease creating frames to compare with or send on the mocked IO.
- Add extension methods for futures that return a `Handle`, such as `send_frame` and `recv_frame`.
Ends up looking something like this:
```rust
let mock = srv.assert_client_handshake().unwrap()
.recv_settings()
.recv_frame(
frames::headers(1)
.request("GET", "https://http2.akamai.com/")
.eos()
)
.send_frame(
frames::headers(1)
.response(200)
)
// send 2 data frames
.send_frame(frames::data(1, &payload[..]))
.send_frame(frames::data(1, &payload[..]).eos())
// gotta end the connection
.map(drop);
```

add ergonomics to testing with frames

---

src/proto/streams/prioritize.rs
src/proto/streams/send.rs
tests/flow_control.rs
tests/prioritization.rs

When a stream is closed, connection level capacity should be released
back to the connection and then assigned to other streams waiting for
capacity.

Fix some flow control bugs

---

src/codec/framed_read.rs
src/codec/mod.rs
tests/codec_read.rs

There was a TODO comment in `Codec` where the maximum frame length was set saying "make this configurable and allow it to be changed during runtime."
I've added methods `get_max_frame_length` and `set_max_frame_length` on `codec::FramedRead` that wrap the underlying methods of the same name on `tokio_io::length_delimited::FramedRead`, and the same methods to `Codec` wrapping the methods on `codec::FramedRead`.
Added a unit test for this, based on the `update_max_frame_len_at_rest()` test in `tokio_io`. Would like to add a test for updating the max frame length when frames are in flight as well, but it'll take a little more work to mock and given that we're just farming this out to `tokio_io`, it'll _probably_ be fine, right?

Make Codec max frame length configurable

---

src/client.rs
src/frame/settings.rs
src/proto/connection.rs
src/proto/streams/recv.rs
src/proto/streams/state.rs
src/server.rs
tests/flow_control.rs
tests/stream_states.rs
tests/support/src/frames.rs
tests/support/src/mock.rs

Only started with a single setting, `initial_window_size`, instead of offer a bunch that aren't actually hooked up. As we want more (and we do), we will have to be sure that the setting actually does what it says.
While I was working on this, and coming up with a test case to make sure it worked, I ended up fixing some other things too... Oh well, they're broken into logical commits.
cc #40 (server config still missing)

Intial Client Configuration

---

src/proto/streams/recv.rs
tests/flow_control.rs

When capacity is released back to the connection and a connection level
window update needs to be sent out, the connection task needs to be
notified in order for the send to actually happen.

Notify connection on connection window expansion

---

src/client.rs
src/codec/framed_read.rs
src/codec/framed_write.rs
src/codec/mod.rs
src/frame/reason.rs
src/frame/settings.rs
src/server.rs
tests/codec_read.rs
tests/stream_states.rs
tests/support/src/frames.rs
tests/support/src/future_ext.rs
tests/support/src/mock.rs
tests/support/src/raw.rs

- Adds `max_frame_size` to client and server builders
- Pushes max_frame_size into Codec
- Detects when the Codec triggers an error from a frame too big
- Sends a GOAWAY when FRAME_SIZE_ERROR is encountered reading a frame
Depends on #87

Configure max frame size

---

src/client.rs
src/server.rs

It seems typical for something like a `tower::NewService` to hold a Builder, and it may need to clone a builder (i.e. out of `self` into a future).

Derive Clone for Builder types

---

src/client.rs
src/codec/framed_read.rs
src/codec/framed_write.rs
src/frame/headers.rs
src/frame/settings.rs
src/proto/connection.rs
src/proto/streams/counts.rs
src/proto/streams/mod.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
tests/push_promise.rs
tests/support/src/frames.rs

- Adds `Client::builder().enable_push(false)` to disable push
- Client sends a GO_AWAY if receiving a push when it's disabled

add Client config to disable server push

---

codecov.yml

We probably don't care about covering code in these directories, so exclude them from test coverage.

Add `fixtures`, `examples`, and `util` to Codecov ignore list

---

examples/akamai.rs
examples/client.rs
src/client.rs
tests/client_request.rs
tests/flow_control.rs
tests/prioritization.rs
tests/push_promise.rs
tests/stream_states.rs
tests/trailers.rs

All other fns have a send prefix.
Relates to #75

Rename Client::request -> send_request

---

src/client.rs
src/codec/error.rs
src/frame/mod.rs
src/frame/stream_id.rs
src/proto/connection.rs
src/proto/streams/mod.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/server.rs
tests/client_request.rs

Closes #48 
No tests... With #64, it'd be pretty easy to add a test to stream_states when a peer tries to open a new stream once the id space is at max. Adding a test that a `UserError` is returned will require adding some way to configure the next stream ID manually, or we'd have a test case submitting some 2 million requests...

check for StreamId overflow

---

src/frame/settings.rs
tests/client_request.rs
tests/support/src/frames.rs
tests/support/src/mock.rs

It actually already works, this just adds a test to prevent regressions.
Closes #27

add test for client sending over max concurrent limit

---

tests/flow_control.rs

I've rewritten the tests `flow_control::stream_close_by_data_frame_releases_capacity()` and `flow_control::stream_close_by_trailers_frame_releases_capacity()` to use the new mock API. This will make modifying these tests a bit easier in order to expect the correct behavior in my [reset on drop branch](https://github.com/carllerche/h2/commits/eliza/reset-on-drop).

Rewrite flow control tests to use newer mock API

---

.travis.yml
src/client.rs
src/codec/framed_read.rs
src/proto/connection.rs
src/proto/streams/recv.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
tests/client_request.rs
tests/flow_control.rs
tests/push_promise.rs

Always install rustfmt since nightly may change underneath it, causing linking to break.
Apply rustfmt

Disallow nightly failures

---

src/frame/headers.rs
src/frame/settings.rs

Projects cannot currently depend on the h2 repo due the following compile errors:
```
error: method is never used: `new`
--> /Users/ver/b/rs/h2/src/frame/headers.rs:265:5
|
265 | /     pub fn new(
266 | |         stream_id: StreamId,
267 | |         promised_id: StreamId,
268 | |         pseudo: Pseudo,
...   |
279 | |         }
280 | |     }
| |_____^
|
note: lint level defined here
--> /Users/ver/b/rs/h2/src/lib.rs:1:9
|
1   | #![deny(warnings, missing_debug_implementations)]
|         ^^^^^^^^
= note: #[deny(dead_code)] implied by #[deny(warnings)]
error: method is never used: `into_parts`
--> /Users/ver/b/rs/h2/src/frame/headers.rs:339:5
|
339 | /     pub fn into_parts(self) -> (Pseudo, HeaderMap) {
340 | |         (self.header_block.pseudo, self.header_block.fields)
341 | |     }
| …
```

Update so dependents can compile

---

.travis.yml

We run codecov after successful test runs. This ~doubles the length of
CI jobs, sicne the codecov run reproduces nearly all tests.
To avoid this, we just run the codecov tests as part of our normal test
script.

Only run tests once in CI

---

.travis.yml

This currently works, but the build is failing because of issue #110. Waiting on #112 to merge this.
Once I get this merged, I'll also work on collapsing some of the build stages to run in parallel, which should help make CI faster.
Fixes #114.

Run h2spec on CI

---

.travis.yml
ci/h2spec.sh

Removed build stages from travis configuration. `rustfmt` and doc publishing run are run on the nightly build while `h2spec` runs on the stable build (as suggested by @carllerche). This also adds the changes to make coverage faster added in #118.
Closes #118.

Make CI build flatter (and therefore faster)

---

codecov.yml

This PR sets the threshold by which code coverage can drop before Codedov marks the commit as failing or notifies Slack to 5%, as requested by @seanmonstar.

Set codecov threshold to 5%

---

examples/akamai.rs
examples/client.rs
src/client.rs
src/proto/connection.rs
src/proto/mod.rs
src/proto/streams/counts.rs
src/proto/streams/mod.rs
src/proto/streams/prioritize.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/store.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
tests/client_request.rs
tests/flow_control.rs
tests/ping_pong.rs
tests/prioritization.rs
tests/push_promise.rs
tests/stream_states.rs
tests/support/mock.rs
tests/support/mod.rs
tests/support/prelude.rs
tests/trailers.rs

The Connection type is a `Future` that drives all of the IO of the
client connection.
The Client type is separate, and is used to send requests into the
connection.
An unresolved question is what order of the tuple is better:
- `let (client, conn) = await!(handshake)?;`
- `let (conn, client) = await!(handshake)?;`

split Client into Connection and Client

---

src/frame/go_away.rs
src/proto/connection.rs
src/proto/streams/send.rs
src/proto/streams/store.rs
src/proto/streams/streams.rs
tests/stream_states.rs

This is a first step to better GOAWAY support (cc #83). This patch will close all streams greater than the last stream ID in the GOAWAY frame, but allow streams less than to still finish.

when receiving a GOAWAY, allow earlier streams to still process

---

src/frame/ping.rs
src/proto/connection.rs
src/proto/ping_pong.rs
tests/ping_pong.rs
tests/support/frames.rs

Adds some extra tests as well, to be sure.
We probably want to expose an API for a user to be able to send pings, to allow them to record latency and otherwise know that the remote is still there, but until we do, these fields are just bloat.

remove unused pieces from PingPong

---

src/hpack/huffman/mod.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
tests/support/mock.rs

Trying to increase robustness and reduce panics, I've swept through the `unimplemented!`s, and converted most of them into something more appropriate. The ones I left required more thought, and are sufficiently rare that I didn't want to block these.

Remove most instances of unimplemented!

---

src/frame/headers.rs
src/server.rs
tests/server.rs
tests/support/frames.rs
tests/support/mod.rs
tests/support/util.rs

Closes #120 
(also includes some rustfmt changes I've forgotten in the past few PRs...)

reset streams when receiving malformed pseudo headers

---

Cargo.toml

Other users of the http crate may depend on crates.io or hyperium/http... This ambiguity leads to compile errors. Depending on crates.io allows dependents to override the repo dependency more easily.

Depend on http:0.1

---

src/client.rs
src/server.rs
tests/flow_control.rs

This enables releasing stream capacity without having the `Body` handle.

Add ReleaseCapacity handle.

---

src/proto/streams/prioritize.rs

The initial window size of both the send and recv flow controllers are
configured from the same setting. The send flow controller should be
configured from the remote's initial window size.
I'm unsure of how to test this.

Use remote window size for send flow control

---

.travis.yml

Tarpaulin – the coverage tool we're using on CI – exits with 0 if a compile error occurred when compiling tests. Since we are currently only building and running tests with Tarpaulin, this means that builds where the tests couldn't be compiled successfully are erroneously being marked as "successful" – see #143 for details.
Closes #143.

Fail CI builds if tests could not be compiled (workaround for #143)

---

src/frame/reason.rs

The change of `Reason` from an enum to a struct results in debug logs showing things like `Reason(3)`. This changes it so it would show `FLOW_CONTROL_ERROR` instead.

custom Debug for Reason

---

src/client.rs
src/frame/settings.rs
src/proto/connection.rs
src/server.rs
tests/client_request.rs
tests/server.rs
tests/support/frames.rs
tests/support/mock.rs

This PR adds `max_concurrent_streams()` methods to the client and server `Builder`s to set the `max_concurrent_streams` setting. I've added unit tests to ensure the correct SETTINGS frame is sent.
Closes #106

Add methods to `{client, server}::Builder` to set max concurrent streams

---

src/client.rs
src/proto/connection.rs
src/proto/streams/flow_control.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/streams.rs
src/server.rs
tests/flow_control.rs
tests/support/mock.rs

We already track how much of the window is "reserved" by body streams, with connection flows having the default initial size of 65,535. As streams reserve some and release some, the connection window gets reset back up to that number (because we always subtract and then add the same amount to it).
This PR adds a new method to allow stating that the target window size is no longer the default, but something else. If the difference from the default is large enough, a WINDOW_UPDATE is sent out (because of our queuing of updates). Besides that, as streams use the connection window, and then release it back, we'll continue to send updates to the remote to get the window back to the target size (again, based on queuing window updates till a threshold is reached).
Closes #101

add set_target_window_size methods to Server and Client

---

src/proto/streams/prioritize.rs
src/proto/streams/send.rs
src/proto/streams/stream.rs
tests/flow_control.rs
tests/support/frames.rs
tests/support/util.rs

* Release stream capacity back to the connection to avoid capacity
leaks.
* Actually notify waiting tasks when capacity becomes available.

Fix some flow control bugs.

---

examples/akamai.rs
examples/client.rs
src/client.rs
tests/client_request.rs
tests/flow_control.rs
tests/prioritization.rs
tests/push_promise.rs
tests/stream_states.rs
tests/trailers.rs

This allows having separate tasks to manage sending bodies and receiving the response without having to wrap `client::Stream` in an `Arc<Mutex<..>>`.

Split response future from `client::Stream`

---

src/proto/mod.rs
src/server.rs

Server-side version of #42. I've rewritten `server::Handshake` to store the inner future with a named type, rather than as a `Box<Future>`. In addition to removing a `Box`, this also means that the `'static` lifetime bounds on the type parameters `T` and `B` can be removed.
The type of the server handshake future is somewhat more complex than the client-side handshake future. Note also that I've had to re-export `proto::streams::Prioritized` as `pub(crate)` from `proto`, as it appears in the type of the handshake future.
I've ran the tests against this branch and everything passes. Since no new functionality was added, I haven't added any additional tests.

Unbox server handshake future

---

examples/client.rs
examples/server-tr.rs
examples/server.rs
src/client.rs
src/lib.rs
src/proto/connection.rs
src/proto/mod.rs
src/proto/peer.rs
src/proto/streams/buffer.rs
src/proto/streams/counts.rs
src/proto/streams/mod.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/store.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
src/server.rs
src/share.rs
tests/support/util.rs

This PR provides a bunch of API cleanup
The first step is to rid of the internal `P: Peer` generic.
All public API types that do not work with the send data frame type are no longer generic.
While calling this function is the last thing that should be done with
the instance, the intent of the h2 library is not to be used directly by
users, but to be used as an implementation detail by other libraries.
Requiring `self` on `send_reset` is pretty annoying when calling the
function from inside a `Future` implementation. Also, all the other fns
on the type take `&mut self`.

API cleanup

---

src/server.rs

Remove `'static` bounds from some types. These are not necessary anymore now that the server handshake has been unboxed.

Loosen some bounds.

---

src/proto/streams/recv.rs
src/proto/streams/streams.rs
src/share.rs
tests/flow_control.rs
tests/stream_states.rs

This function returns true if the `RecvStream` has reached an end of
stream state. This is intended to replace `is_empty` which has confusing
behavior.

Add RecvStream::is_end_stream.

---

src/proto/streams/prioritize.rs

I was somewhat confused by `frame.map(|_| unreachable!())` here, so after @seanmonstar explained to me why this code was unreachable, I thought I'd add a message to the `unreachable!()` macro to prevent future confusion.

Make panic message in unreachable!() explain why

---

src/error.rs

When an h2 error code is known, applications may care to know about the
specific error. For example, an application may want to report per-code
metrics or handle `ENHANCE_YOUR_CALM` specially.

Expose h2::Error::reason

---

src/proto/streams/prioritize.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
tests/stream_states.rs
tests/support/future_ext.rs

I've added a unit test ensuring that we don't initialize streams in the idle state such that they may be moved into reserved/open out of order. I've also added an assertion in `Prioritize::pop_frame` that the stream ID of any headers frame that opens a new stream is greater than all previously sent stream IDs.
Closes #11

Add test and assertion for idle state handling

---

src/codec/error.rs
src/frame/headers.rs
src/proto/streams/send.rs
tests/client_request.rs
tests/server.rs
tests/support/frames.rs

- When receiving, return a PROTOCOL_ERROR.
- When sending, return a user error about malformed headers.
While #36 mentions stripping the headers, this PR actually returns a `UserError` instead.
Closes #36

reject connection-specific headers

---

src/proto/streams/prioritize.rs
tests/prioritization.rs
tests/support/mod.rs
tests/support/notify.rs
tests/support/prelude.rs

This patch fixes a bug that prevents sent data from being flushed to the
socket.
When data is sent, the task managing the connection must be notified. A
guard exists that prevents unnecessary notification of the connection
when the stream does not have any send capacity. However, this guard was
buggy. Instead of notifying the connection if *any* data can be sent, it
notified the connection only when *all* data could be sent.
This patch fixes the check as well as adds some tests that ensure the
connection task is notified.

Fix flow control bug

---

src/client.rs
src/codec/error.rs
src/frame/headers.rs
src/proto/peer.rs
src/proto/streams/send.rs
src/proto/streams/streams.rs
src/server.rs
tests/client_request.rs
tests/support/frames.rs
tests/support/prelude.rs

This patch adds checks for the request URI and rejects invalid URIs. In
the case of forwarding an HTTP 1.1 request with a path, an "http" pseudo
header is added to satisfy the HTTP/2.0 spec.
`convert_send_message` is removed from the `Peer` trait as it is not
needed to be generic. The client version now returns an error if the request
is invalid.
This PR depends on https://github.com/hyperium/http/pull/147.
Closes #179

Client should validate request URI.

---

src/client.rs
src/server.rs

As the title says. This removes all but one struct level bound on the client/server `Handshake` future struct.

Remove most struct level bounds on handshake types

---

src/proto/streams/recv.rs
src/share.rs

This patch removes a panic in `poll_trailers` that is triggered if
`poll_trailers` is called before `poll_data` returns `None`.
This is done by always trying to notify the receive task when
`poll_data` returns None and there already is pending trailers.

Don't panic on poll_trailers called out of order.

---

src/codec/framed_read.rs
src/codec/framed_write.rs
src/frame/headers.rs
tests/codec_write.rs

Large header sets might require being split up across multiple frames.
This patch adds support for doing so.

Support writing continuation frames.

---

src/server.rs

This patch makes a tiny change to remove invalid brackets in the
comment for server module example.
Due to invalid brackets, current crate docs jumps to invalid URL from
the link of `prior knowledge`.
https://carllerche.github.io/h2/h2/server/index.html#example

Remove invalid brackets

---

src/client.rs

Since `convert_poll_message()` does not set protocol version as
HTTP/2.0, responses client received always display `version:
HTTP/1.1`. 
This patch adds `HTTP/2.0` to the response.
Fixes https://github.com/carllerche/h2/issues/204

Add protocol version to response for client

---

src/proto/streams/prioritize.rs
tests/flow_control.rs

This assertion just seems wrong. It doesn't matter if there is still available window for the stream if there was room to buffer the frame to send. Or am I misunderstanding what this assertion is trying to check?
Closes #208

remove erroneous assert when stream has buffered send data

---

.travis.yml
README.md
examples/akamai.rs
examples/client.rs
examples/server-tr.rs
examples/server.rs
src/client.rs
src/server.rs
tests/client_request.rs
tests/codec_write.rs
tests/flow_control.rs
tests/ping_pong.rs
tests/prioritization.rs
tests/push_promise.rs
tests/server.rs
tests/stream_states.rs
tests/support/prelude.rs
tests/trailers.rs

Misc renames to try to increase consistency across `client` and `server` modules.
* `server::Server` -> `server::Connection`.
* `client::Client` -> `client::SendRequest` (there already is a `client::Connection`).
* `server::Respond` -> `server::SendResponse`.
This also moves the `builder` and `handshake` fns from `client::Client` -> `client::Connection` as well as change the type orders in the tuple returned by the `server::Handshake` future.
Fixes #154

Misc renames

---

Cargo.toml
src/client.rs
src/codec/error.rs
src/codec/framed_read.rs
src/codec/mod.rs
src/frame/headers.rs
src/frame/settings.rs
src/hpack/decoder.rs
src/hpack/mod.rs
src/hpack/test/fixture.rs
src/hpack/test/fuzz.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/streams.rs
src/server.rs
tests/client_request.rs
tests/codec_read.rs
tests/codec_write.rs
tests/push_promise.rs
tests/server.rs
tests/support/frames.rs
tests/support/mock.rs
tests/support/mod.rs
tests/support/prelude.rs

This, uh, grew into something far bigger than expected, but it turns out, all of it was needed to eventually support this correctly.
- Adds configuration to client and server to set [SETTINGS_MAX_HEADER_LIST_SIZE](http://httpwg.org/specs/rfc7540.html#SETTINGS_MAX_HEADER_LIST_SIZE)
- If not set, a "sane default" of 16 MB is used (taken from golang's http2)
- Decoding header blocks now happens as they are received, instead of buffering up possibly forever until the last continuation frame is parsed.
- As each field is decoded, it's undecoded size is added to the total. Whenever a header block goes over the maximum size, the `frame` will be marked as such.
- Whenever a header block is deemed over max limit, decoding will still continue, but new fields will not be appended to `HeaderMap`. …

SETTINGS_MAX_HEADER_LIST_SIZE

---

src/client.rs

This provides a functional future API for waiting for SendRequest
readiness. This follows the pattern found in [tower].
[tower]: https://github.com/tower-rs/tower/blob/master/src/lib.rs#L242

Implement SendRequest::ready.

---

src/client.rs

The END_STREAM flag is set when the stream is ending, so it needs to be
false if we're sending data.

Fix documentation for end_of_stream

---

src/client.rs
src/proto/connection.rs
src/proto/peer.rs
src/proto/streams/counts.rs
src/proto/streams/recv.rs
src/proto/streams/streams.rs
src/server.rs
tests/client_request.rs
tests/codec_read.rs
tests/codec_write.rs
tests/flow_control.rs
tests/ping_pong.rs
tests/server.rs
tests/stream_states.rs

When all Streams are dropped / finished, the Connection was held
open until the peer hangs up. Instead, the Connection should hang up
once it knows that nothing more will be sent.
To fix this, we notify the Connection when a stream is no longer
referenced. On the Connection poll(), we check that there are no
active, held, reset streams or any references to the Streams
and transition to sending a GOAWAY if that is case.
These changes cause the example to work as expected (exiting when finished getting the response), but break other tests that are not expecting the connection to hang out.

When Streams are dropped, close Connection (#221)

---

Cargo.toml
examples/akamai.rs
examples/client.rs
examples/server.rs
tests/client_request.rs
tests/codec_read.rs
tests/codec_write.rs
tests/flow_control.rs
tests/ping_pong.rs
tests/prioritization.rs
tests/push_promise.rs
tests/server.rs
tests/stream_states.rs
tests/trailers.rs

Upgrade to env_logger 0.5 and log 0.4 so that projects that use those
versions don't have to build both those versions and the older ones
that h2 is currently using.
Don't enable the regex support in env_logger. Applications that want
the regex support can enable it themselves; this will happen
automatically when they add their env_logger dependency.
Disable the env_logger dependency in quickcheck.
The result of this is that there are fewer dependencies. For example,
regex and its dependencies are no longer required at all, as can be
seen by observing the changes to the Cargo.lock. That said,
env_logger 0.5 does add more dependencies itself; however it seems
applications are going to use env_logger 0.5 anyway so this is still
a net gain.
Submitted on behalf of Buoyant, Inc.
Signed-off-by: …

Upgrade to env_logger 0.5 & log 0.4; reduce related dependencies

---

Cargo.toml
src/lib.rs
src/proto/streams/store.rs

Avoid the need for indexmap-based applications to build ordermap,
which is the old name for indexmap.
Signed-off-by: Brian Smith <brian@briansmith.org>

Upgrade ordermap dependency to indexmap.

---

src/proto/streams/prioritize.rs
src/proto/streams/store.rs
tests/prioritization.rs
tests/support/mod.rs

This assert does not hold as many streams can be pushed into
pending_capacity during a call to send_data(). See issue #224
for more discussion and sign-off.

Remove assert around self.pending_capacity.is_empty() (#224)

---

src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/stream.rs
tests/client_request.rs

If `client::SendRequest` had parked a future with `poll_ready`, and there is a connection error (not eof), that future was never notified.
Also removes `open_task`, as it was dead code.

notify send_tasks when there is a connection error

---

src/proto/streams/prioritize.rs

It isn't immediately obvious why the connection supports buffering
requests. The reason is that it models the futures' mpsc channel
behavior.
This patch adds a comment explaining this.

Add a comment explaining what pending_open is for

---

tests/prioritization.rs

Running `cargo test --features unstable` was failing because env_logger was already initiated. Use `try_init` like every other test to fix this.

Fix tests by switching to env_logger::try_init

---

src/proto/streams/prioritize.rs
src/proto/streams/send.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs

Because external users of h2 are allowed to `send_request()` and `send_data()` without blocking, a stream can get pushed into the pending_open queue (waiting for number of streams to go down), and also the pending_send queue (waiting for capacity on the stream / connection). My proposed solution is to prevent streams from being pushed into pending_send queue as streams put in the queue are scheduled to be executed + data should not be sent for a stream that is not open.
There are also newly added asserts that a stream should never be in pending_send and pending_open at the same time.

Prevent pushing a stream into both pending_send + pending_open

---

src/frame/headers.rs
tests/client_request.rs
tests/prioritization.rs
tests/support/prelude.rs

The HTTP/2.0 specification requires that the path pseudo header is never
empty for requests unless the request uses the OPTIONS method.
This is currently not correctly enforced.
This patch provides a test and a fix.

Normalize HTTP request path.

---

src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/streams.rs
tests/client_request.rs

So, I thought this issue was solved with #235, but actually what was happening was I had both these fixes + #235 previously, and removed these fixes because they didn't seem to be necessary (test code worked fine). Unfortunately, turns out there a race condition external to the h2 crate that was hiding this issue (adding additional logging causes this issue again).
The issue:
Streams that have pending send data and also receive a peer reset are not counted as `is_closed()` after reset. Because these streams were opened, they increment `num_send_streams` which is an internal tracker of the number of open send streams checked against `max_send_streams`. Therefore the connection will believe streams are still in-flight + won't open new streams.
The fix:
Properly call …

Streams receiving peer reset clear pending send

---

src/client.rs

The test is not supposed to actually run, but the `select` is not fast
enough on Travis.

Fix client doc test

---

src/client.rs
src/proto/connection.rs
src/proto/streams/counts.rs
src/proto/streams/mod.rs
src/server.rs

Problem: Establishing a connection to some provider and using the `poll_ready()` function to determine when there is space to establish new streams means that we can send up to `usize::MAX` streams until receiving a `Settings` frame from the remote peer.
Solution: Allow callers to specify an `initial_max_send_streams` which can be used until receiving the `Settings` frame. This will prevent using extraneous bandwidth and an extraneous amount of REFUSED_STREAM resets and can scale up or down the number of streams without causing unnecessary delays.
The default behavior is to keep the `initial_max_send_streams` at `usize::MAX` to keep functionality the same.

Add initial_max_send_streams() as builder option

---

src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/state.rs
tests/stream_states.rs

Fixes #246. Fixes runconduit/conduit#607.
An issue currently exists where `h2` will panic when a stream transitions from `HalfClosed(remote)` to `Closed(Cause::EndStream)` by enqueuing an EOS frame, and then receives a `RST_STREAM` frame _before_ the queued EOS frame is sent.
In this case, the `expect` in `prioritize::pop_frame` https://github.com/carllerche/h2/blob/f8baeb7211985834acaf7ecc70548aafd5d9ef6d/src/proto/streams/prioritize.rs#L693-L694 is called on a frame which does _not_ have a scheduled reset, because it is in the `Closed(Cause::EndStream)` state. However, the guard which skips this code when the stream is peer reset https://github.com/carllerche/h2/blob/f8baeb7211985834acaf7ecc70548aafd5d9ef6d/src/proto/streams/prioritize.rs#L584-L586 doesn't cause us to skip in this case, …

recv_reset resets closed streams with queued EOS frames

---

src/client.rs
src/server.rs

There is currently no way to configure the initial target window size
for connections. The `Builder::initial_connection_window_size` utility
makes this configurable so that all new server connections have this
target window size set.

Add initial_connection_window_size to Builders

---

src/frame/headers.rs
src/hpack/header.rs
src/proto/connection.rs
src/proto/streams/streams.rs

Ran a fuzzer and found a few places where we were panicking instead of returning errors.

Add some missing bounds checks.

---

src/proto/streams/prioritize.rs
tests/stream_states.rs
tests/support/mock.rs

In `clear_queue` we drop all the queued frames for a stream, but this doesn't
take into account a buffered frame inside of the `FramedWrite`. This can lead
to a panic when `reclaim_frame` tries to recover a frame onto a stream that has
already been destroyed, or in general cause wrong behaviour.
Instead, let's keep track of what frame is currently in-flight; then, when we
`clear_queue` a stream with an in-flight data frame, mark the frame to be
dropped instead of reclaimed.

Avoid reclaiming frames for dead streams.

---

src/proto/connection.rs
src/proto/streams/counts.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/store.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/stream_states.rs

In an effort to test #261, I added new assertions checking that stream counts is zero when the connection finalizes and that stream state gets released (the slab is empty on drop).
Adding these assertions uncovered a number of bugs. This PR fixes the discovered bugs.
I would recommend reviewing each commit individually as they are pretty independent.

Misc bug fixes

---

src/codec/error.rs
src/proto/mod.rs
src/proto/streams/mod.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
src/server.rs
src/share.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/server.rs

Allows for listening for `RST_STREAM`s that may be sent before a `Response` has been generated, and cancel everything.

add server::SendResponse::poll_reset to listen for reset streams

---

src/client.rs
src/proto/mod.rs
src/proto/streams/mod.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/client_request.rs

Because `self.pending` doesn't necessarily get cleaned up in a timely fashion -
rather, only when the user calls `poll_ready()` - it was possible for it to
refer to a stream that has already been closed. This would lead to a panic the
next time that `poll_ready()` was called.
Instead, use an `OpaqueStreamRef`, bumping the refcount.
A change to an existing test is included which demonstrates the issue.

Promote SendRequest::pending to an OpaqueStreamRef.

---

src/server.rs
tests/h2-support/src/mock.rs
tests/h2-tests/tests/server.rs

when the underlying IO returns 0 on read, we must stop polling it since
it's closed. Otherwise we'll be stuck in a tight loop.
this fixes https://github.com/sfackler/rust-openssl/issues/949

fix tight loop on aborted connection

---

src/client.rs
src/frame/stream_id.rs
src/lib.rs
src/proto/streams/streams.rs
src/server.rs
src/share.rs

Problem:
Applications may want to access the underlying h2 stream ID for
diagnostics, etc. Stream IDs were not previously exposed in public APIs.
Solution:
The `frame::StreamId` type is now publically exported and has RustDoc
comments. The public API types `SendStream`, `RecvStream`, 
`ReleaseCapacity`, `client::ResponseFuture`, and `server::SendResponse` 
now all have `stream_id` methods which return the stream ID of the 
corresponding stream.
Closes #289.
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

Add `stream_id` accessors to public API types

---

src/proto/streams/prioritize.rs
src/proto/streams/send.rs
src/proto/streams/stream.rs
tests/h2-tests/tests/client_request.rs

This fixes a panic that would otherwise occur in some cases. A test
demonstrating said panic is included.

Prevent `pending_open` streams from being released.

---

src/proto/go_away.rs
tests/h2-support/src/mock.rs
tests/h2-tests/tests/server.rs

Prior to this change, after having sent the the GOAWAY capping the last known stream ID, the server would wait until its active streams had finished, and then try to trigger `go_away_now`. However, since the last stream ID and reason were the same, it would prevent sending the duplicate frame, and then loop. This change now notices the new `go_away_now` call, and allows the server to finish.
The tests were adjusted to make sure the client received an EOF, instead of just closing the client in the test. This showed that we weren't doing so, and the change fixes the test again.

fix graceful shutdown to close once idle

---

src/lib.rs

This should fix building the docs on docs.rs.
Closes #306

set deny(warnings) only when cfg(test)

---

tests/h2-support/src/frames.rs

I needed this while writing tests for tower-h2.
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

Add Reset::INTERNAL_ERROR helper to test support

---

src/frame/headers.rs
tests/h2-support/src/assert.rs
tests/h2-tests/tests/codec_read.rs

Got stuck on this using the PUSH frame headers for the first time while implementing client side push support.
Should the HPACK decoder have thrown an error?

Fix push promise frame parsing

---

Cargo.toml
examples/akamai.rs
examples/client.rs
examples/server.rs
src/client.rs
src/server.rs

The old `tokio-core` crate is deprecated in favour of the `tokio` crate,
which also provides the new multithreaded Tokio runtime. Although `h2`
is generic over the runtime, the examples do depend on `tokio`. 
This branch update the example code to use the new `tokio` library
rather than `tokio-core`.
For the most part, this was pretty trivial --- simply replacing
`handle.spawn(...)` with `tokio::spawn(...)` and `core.run(...)` with
`tokio::run(...)`. There were a couple of cases where error and item
types from spawned futures had to be mapped to `(), ()`. Alternatively,
this could have been avoided by using the single-threaded runtime and
calling `block_on` instead to await the value of those futures, but I
thought it was better to reduce the amount of tokio-specific code in the
examples. …

Update examples to use new Tokio

---

src/codec/mod.rs

Until tokio-rs/tokio#680 is resolved, we should allow using deprecated
APIs in the codec module.

Disable length_delimited deprecation warning.

---

src/proto/streams/send.rs
tests/h2-tests/tests/client_request.rs

Because `send_reset` called `recv_err`, which calls `reclaim_all_capacity`,
which eventually calls `transition(stream, ..)` -- all of which happens _before_
the RESET frame is enqueued -- it was possible for the stream to get unlinked
from the store (if there was any connection-level capacity to reassign). This
could then cause the stream to get "leaked" on drop/EOF since it would no longer
be iterated.
Fix this by delaying the call to `reclaim_all_capacity` _after_ enqueueing the
RESET frame.
A test demonstrating the issue is included.

Avoid prematurely unlinking streams in `send_reset`, in some cases.

---

src/proto/streams/streams.rs
tests/h2-tests/tests/stream_states.rs

We think this fixes #312 -- for window updates, we should be checking against the client-initiated send streams, not the server-initiated recv streams.

Check whether the send side is not idle, not the recv side

---

src/proto/streams/send.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/flow_control.rs

I believe this was an oversight - a stream that is reset can still have some
capacity assigned to it (e.g. if said capacity was assigned in the same poll as
the reset), which should be redistributed.
Note that `Send::recv_reset` is now identical to `Send::recv_err`; I'm not sure if they should be unified.

Reassign capacity from reset streams.

---

src/proto/streams/streams.rs

It is not obvious that attempting to print the
value of a struct could cause a deadlock. To avoid
this, this patch does not lock the mutex when generating
a debug representation of the h2 struct.

Avoid locking when printing

---

src/proto/streams/streams.rs
tests/h2-tests/Cargo.toml
tests/h2-tests/tests/hammer.rs

Currently, there is a race condition that occurs when
`Arc::strong_count` is used to detect whether client handles have been
dropped and a connection could shut down. If the connection manager's
task is notified before the arc ref is dropped, it will see that the ref
count is greater than 1 and go back to sleep, resulting in deadlock.
This branch solves the race by manually counting the number of
`StreamRef`s inside the lock on the shared state, rather than relying on
the `Arc` ref count. I've included a hammer test based on the
reproduction described in #326, and confirmed that it hangs on master
but runs to completion on this branch.
Fixes #326
Signed-off-by: Eliza Weisman <eliza@buoyant.io>

Fix race in stream ref count

---

src/server.rs

Currently, when a `h2` server receives a HEADERS frame with malformed
pseudo-headers, it logs which pseudo-heade was malformed at the debug
level before sending a reset. This behaviour is correct. However, it can
be difficult to debug misbehaving clients, as the server's log message
doesn't include the *value* of the invalid pseudo-header, or indicate
*why* it was incorrect. 
This branch changes the log message to include both the value of the
malformed header and the error that caused it to be rejected. 
For example, here is the output from the test
`server::recv_invalid_authority`, before and after making this change.
Before:
```
...
DEBUG 2019-01-23T19:16:28Z: h2::server: malformed headers: malformed authority
...
```
After:
```
...
DEBUG 2019-01-23T19:15:37Z: h2::server: malformed …
```

Log more information when rejecting malformed pseudo-headers

---

src/proto/streams/send.rs

This is a low-profile bug, so I'm not creating an issue for it.

Fixed incorrect order of arguments in send_reset trace.

---

src/client.rs

Simply declaring the `Handshake` in another type shouldn't require `T: IntoBuf`...

Loosen bounds on Handshake struct

---

src/proto/connection.rs
src/proto/streams/counts.rs
src/proto/streams/store.rs
src/proto/streams/streams.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/push_promise.rs
tests/h2-tests/tests/stream_states.rs

Testing some stuff out for gRPC, I noticed that if a `SendStream` sends a local reset, and a task is parked waiting for more data from a `RecvStream`, the recv stream task won't get notified.
The new test was hanging until the source changes fixed it.

Notify RecvStream tasks if SendStream sends a local reset

---

src/hpack/decoder.rs
src/hpack/encoder.rs
src/hpack/table.rs
src/hpack/test/fuzz.rs

- Fixes panic if a "resume" had to pause at a header with a repeat name.
- Fixes erroneous name index usage when repeated header used an index of a header that had evicted itself.

Header encoding fixes

---

src/codec/error.rs
src/codec/framed_write.rs
src/frame/headers.rs
src/hpack/mod.rs
src/proto/streams/send.rs
src/proto/streams/streams.rs

If any single header value was bigger than the write buffer, we'd write a CONTINUATION frame, and then get ready to write the header after. But since the write buffer doesn't grow in size, we'd loop on that condition forever.
- The immediate fix checks if the `CONTINUATION` frame that was written is empty. Instead of looping forever, this will panic, as it's now considered an internal bug.
- So as to not reach the panic, `HEADERS` frames are now checked that they don't contain a header that would be larger than the write buffer.
- Lastly, since this was found with a 6000 length header, the write buffer size has been increased from 4kb to 16kb.

Fix write loop when a header is too big to encode

---

src/proto/streams/prioritize.rs
tests/h2-support/src/prelude.rs

Try as I might, I can't seem to trigger the panic in #362, but looking at the backtrace from that issue, it seems quite likely that the stream received a RST_STREAM while it was waiting for window capacity, and so when calling `recv_reset` and the capacity is released back to the connection, it enters `counts.transition` a second time. That nested `transition` unlinks the pointer, and the outer `transition` panics.

Prevent trying to assign capacity to streams that were just reset

---

src/server.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/server.rs

The code before *tried* to allow these requests, but then the `request::Builder` would error trying to construct a `Uri` with only the scheme and path. Now, if there is no authority, the scheme is dropped.
Closes #345

allow servers to receive requests without an :authority header

---

src/codec/framed_read.rs
src/lib.rs
src/proto/peer.rs
src/proto/streams/recv.rs
src/proto/streams/state.rs
src/proto/streams/streams.rs
src/server.rs

Currently, there are many cases where `h2` will fail a connection or
stream with a PROTOCOL_ERROR, without recording why the protocol error
occurred. Since protocol errors may result from a bug in `h2` or from a
misbehaving peer, it is important to be able to debug the cause of
protocol errors.
This branch adds a log line to almost all cases where a protocol error
occurs. I've tried to make the new log lines consistent with the
existing logging, and in some cases, changed existing log lines to make
them internally consistant with other log lines in that module. I have
_not_ tried to enforce a single style for log lines across all modules,
however, as the debug-level in some modules uses a different style than
the trace logging elsewhere. Presumably this is because it is expected
to be …

Log protocol errors

---

src/proto/streams/streams.rs

[Trailers without EOS](https://httpwg.org/specs/rfc7540.html#HttpSequence):
> An endpoint that receives a HEADERS frame without the END_STREAM flag set after receiving a final (non-informational) status code MUST treat the corresponding request or response as malformed (Section 8.1.2.6).
[Malformed messages](https://httpwg.org/specs/rfc7540.html#malformed):
> Malformed requests or responses that are detected MUST be treated as a stream error (Section 5.4.2) of type PROTOCOL_ERROR.

Fix trailers without EOS flag to be a stream instead of connection error

---

src/client.rs

With this change, `Handshake` can now implement auto traits even if `B` doesn't (like `Send` or `Unpin`).

Adjust client::Handshake's PhantomData since it doesn't own a buffer

---

ci/h2spec.sh
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/streams.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/stream_states.rs

Re-opening of #375, with an adjustment:
The forgotten check for HEADERS is only done on the client side. The rationale is that the *client* can send a request, and then later a RST_STREAM and then forget about the stream while the server HEADERS were in transit. A *server* however will **never** reset a stream before receiving the request HEADERS.
This distinction is also done in golang-http2, grpc-go, and nghttp2. I'm hopeful this makes h2spec still pass.

Send RST_STREAM instead of GOAWAY if stream may have been forgotten

---

src/hpack/test/fuzz.rs
src/lib.rs

Test fail to build on current nightly due to deprecation warning.

chore: 2018 edition clean up

---

Cargo.toml

If you remove the dev-dependencies from the `Cargo.toml` (or use this crate as a non-path dependency in a project which doesn't pull in all of Tokio) you will get a build failure like:
```
Checking h2 v0.2.0-alpha.0 (/Users/nemo157/sources/h2)
error[E0432]: unresolved import `tokio_io::AsyncWriteExt`
--> src/client.rs:154:39
|
154 | use tokio_io::{AsyncRead, AsyncWrite, AsyncWriteExt};
|                                       ^^^^^^^^^^^^^
|                                       |
|                                       no `AsyncWriteExt` in the root
|                                       help: a similar name exists in the module: `AsyncWrite`
error[E0599]: no method named `write_all` found for type `T` in the current scope
--> src/client.rs:1142:12
|
1142 | …
```

Add necessary features for tokio-io

---

Cargo.toml
examples/akamai.rs

This PR brings the rustls and webpki current (resolving some version conflicts with ring)  
It also leverages the tokio-0.2 branch to make the akamai example work^H^H^H^Hcompile again.

fixing the akamai example to work with tokio-0.2

---

src/frame/go_away.rs
tests/h2-tests/tests/codec_read.rs

While this currently doesn't allow *sending* debug data, it can be useful to see when logging *why* a connection is being closed.

Decode debug_data in GOAWAY frames

---

Cargo.toml
src/client.rs
src/server.rs
src/share.rs
tests/h2-support/Cargo.toml

Until 1.0, it's not really fair to call other dependencies "unstable".

Rename unstable-stream feature to stream

---

src/server.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/server.rs

If the :method is CONNECT the :scheme and :path pseudo-header fields MUST be omitted
This is for #234

Handle :scheme and :path in CONNECT

---

src/proto/streams/send.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/server.rs
tests/h2-tests/tests/stream_states.rs

Receiving a GOAWAY should update the max *send* ID, it shouldn't affect
the max recv.

Fix receiving a GOAWAY frame from updating the max recv ID

---

Cargo.toml

This doesn't really have any effect unless you use `cargo -Zfeatures=dev_dep`, but `tokio::sync` is only used in tests.

Move "sync" tokio feature to dev-dependencies

---

src/proto/streams/store.rs

I don't believe this is ensuring anything truly important, it's just checking that we try our best to clean up all the streams. In some cases (like the connection task being canceled), there's nothing we can do, so don't panic in users' applications.
@carllerche you added this assert, so sanity check please.
Closes #417

Change store debug_assert to only run in tests

---

Cargo.toml
src/client.rs
src/codec/framed_read.rs
src/codec/framed_write.rs
src/frame/go_away.rs
src/frame/headers.rs
src/frame/ping.rs
src/frame/reset.rs
src/frame/settings.rs
src/frame/window_update.rs
src/hpack/decoder.rs
src/lib.rs
src/proto/connection.rs
src/proto/ping_pong.rs
src/proto/settings.rs
src/proto/streams/counts.rs
src/proto/streams/flow_control.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/store.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
src/server.rs
tests/h2-tests/Cargo.toml
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/stream_states.rs
tests/h2-tests/tests/trailers.rs

Like https://github.com/hyperium/hyper/pull/2204, this PR switches from `log` to `tracing`. It's a slightly noisy diff because I didn't want to make a _big_ change to `h2` in this PR.

feat(lib): switch from log to tracing

---

src/proto/streams/streams.rs

There was a different misuse of `refs` in `next_incoming`, preventing the overflow from happening in the tests.
Fixes #424, closes #425

Fix overflow panic with push_request

---

Cargo.toml
src/client.rs
src/codec/framed_read.rs
src/codec/framed_write.rs
src/hpack/decoder.rs
src/hpack/encoder.rs
src/hpack/table.rs
src/proto/connection.rs
src/proto/peer.rs
src/proto/streams/prioritize.rs
src/server.rs
tests/h2-support/Cargo.toml
tests/h2-support/src/lib.rs
tests/h2-support/src/prelude.rs
tests/h2-support/src/trace.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/codec_read.rs
tests/h2-tests/tests/codec_write.rs
tests/h2-tests/tests/flow_control.rs
tests/h2-tests/tests/ping_pong.rs
tests/h2-tests/tests/prioritization.rs
tests/h2-tests/tests/push_promise.rs
tests/h2-tests/tests/server.rs
tests/h2-tests/tests/stream_states.rs
tests/h2-tests/tests/trailers.rs

We've adopted `tracing` for diagnostics, but currently, it is just being
used as a drop-in replacement for the `log` crate. Ideally, we would
want to start emitting more structured diagnostics, using `tracing`'s
`Span`s and structured key-value fields.
A lot of the logging in `h2` is already written in a style that imitates
the formatting of structured key-value logs, but as textual log
messages. Migrating the logs to structured `tracing` events therefore is
pretty easy to do. I've also started adding spans, mostly in the read
path.
Finally, I've updated the tests to use `tracing` rather than
`env_logger`. The tracing setup happens in a macro, so that a span for
each test with the test's name can be generated and entered. This will
make the test output easier to read if multiple tests are …

[WIP] start adding `tracing` spans to internals

---

src/proto/streams/stream.rs
tests/h2-tests/tests/client_request.rs

Per https://tools.ietf.org/html/rfc7540#section-8.1.2.6
> A response that is defined to have no payload, as described in [RFC7230], Section 3.3.2, can have a non-zero content-length header field, even though no content is included in DATA frames.
Without this patch, h2 errors with ` recv_data: content-length overflow; stream=StreamId(1); len=0;` when empty DATA frame is received.

Allow responses of HEAD requests to have empty DATA frames

---

Cargo.toml
src/codec/framed_write.rs

Tokio's `AsyncWrite` trait once again has support for vectored writes in
Tokio 0.3.4 (see tokio-rs/tokio#3149.
This branch re-enables vectored writes in `h2`.
This change doesn't make all that big of a performance improvement in
Hyper's HTTP/2 benchmarks, but they use a `BytesMut` as the buffer.
With a buffer that turns into more IO vectors in `bytes_vectored`, there
might be a more noticeable performance improvement.
I spent a bit trying to refactor the flush logic to coalesce into fewer
writev calls with more buffers, but the current implementation seems
like about the best we're going to get without a bigger refactor. It's
basically the same as what `h2` did previously, so it's probably fine.

re-enable vectored writes

---

Cargo.toml
examples/akamai.rs
src/codec/framed_write.rs
src/hpack/decoder.rs
src/proto/streams/prioritize.rs
tests/h2-fuzz/Cargo.toml
tests/h2-support/Cargo.toml
tests/h2-support/src/mock.rs
tests/h2-tests/Cargo.toml
tests/h2-tests/tests/flow_control.rs

WIP because Tokio and Bytes aren't released yet, this uses git dependencies for now which we'll need to fix before merging. But this gets the code fixes ready.

Update to Tokio and Bytes 1.0

---

src/proto/ping_pong.rs
src/server.rs

The `compare_and_swap` method on atomics is now deprecated in favor
of `compare_exchange`.
Since the author of #510 closed that PR, this is just #510 with rustfmt run.
I also removed an unnecessary trailing semicolon that the latest rust
compiler now complains about.

 Replace deprecated compare_and_swap with compare_exchange

---

src/client.rs
src/proto/connection.rs
src/proto/streams/counts.rs
src/proto/streams/streams.rs
src/server.rs

This PR adds accessors to `client::Connection` and `server::Connection`
that return the send stream concurrency limit on that connection, as
negotiated by the remote peer. This is part of issue #512.
I think we probably ought to expose similar accessors for other
settings, but I thought it was better to add each one in a separate,
focused PR.

add `Connection::max_concurrent_send_streams`

---

Cargo.toml
src/client.rs
src/server.rs

The `tracing_futures` dependency is no longer needed since `tracing` v0.1.21

Remove the obsolent tracing-future dependency

---

Cargo.toml

This crate depends on it anyway, and by explicitly turning it on we avoid unreliable platform target detection that causes build failures on some platforms.

Explicitly enable the `std` feature of indexmap

---

src/client.rs
src/codec/framed_write.rs
src/proto/connection.rs
src/proto/mod.rs
src/proto/streams/mod.rs
src/proto/streams/prioritize.rs
src/proto/streams/streams.rs

Didn't see #484 until after the fact so I can remove that commit if desired, it is arguably a cleaner separation though since it extracts a separate and private struct instead of passing multiple parameters.

Make some functions less-generic to reduce binary bloat

---

src/frame/headers.rs
src/proto/streams/recv.rs
src/proto/streams/state.rs
tests/h2-tests/tests/client_request.rs

Fixes #515
This ignores (drops) header frames when the status is 1xx. 
Currently it allows multiple 1xx responses in a row. I couldn't find whether this is forbidden, but I've left it allowed, as I can imagine 103 early hints being followed by 100 continue.
There's no API to retrieve the data from the 1xx frames. Such API could look similar to push promises, but the existing push promise implementation is non-trivial, so I'll leave it for later.

Ignore 1xx frames

---

src/client.rs
src/proto/connection.rs
src/proto/streams/counts.rs
src/proto/streams/streams.rs
src/server.rs

This commit adds accessors to `client::Connection` and
`server::Connection` that return the current value of the
`SETTINGS_MAX_CONCURRENT_STREAMS` limit that has been sent by this peer
and acknowledged by the remote.
This is analogous to the `max_concurrent_send_streams` methods added in
PR #513. These accessors may be somewhat less useful than the ones for
the values negotiated by the remote, since users who care about this
limit are probably setting the builder parameter. However, it seems
worth having for completeness sake --- and it might be useful for
determining whether or not a configured concurrency limit has been acked
yet...
Part of #512

add `Connection::max_concurrent_recv_streams`

---

src/proto/streams/state.rs
tests/h2-tests/tests/client_request.rs

I couldn't find a way to repro the panic from a test.

Skip 1xx frames in more states (fixes #524)

---

src/proto/streams/recv.rs
src/proto/streams/store.rs

This allows to use `h2` on wasm platforms which lack an `Instant::now` implementation by setting the number of streams to 0 with: `h2::client::Builder::max_concurrent_reset_streams`.
Resolves #511

Do not use `Instant::now` when zero reset streams are configured.

---

src/proto/streams/streams.rs
tests/h2-tests/tests/server.rs

If a user stored a `StreamRef` to the same stream in the request or
response extensions, they would be dropped while the internal store lock
was held. That would lead to a deadlock, since dropping a stream ref
will try to take the store lock to clean up.
Clear extensions of Request and Response before locking store, prevent
this.
Fixes hyperium/hyper#2621

Fix potential hang if extensions contain same StreamRef

---

src/codec/error.rs
src/codec/framed_write.rs
src/frame/headers.rs
src/hpack/decoder.rs
src/hpack/encoder.rs
src/hpack/huffman/mod.rs
src/hpack/mod.rs
src/hpack/test/fixture.rs
src/hpack/test/fuzz.rs
src/proto/streams/send.rs
tests/h2-support/src/prelude.rs

This completely refactors how headers are hpack-encoded.
Instead of trying to be clever, constructing frames on the go
while hpack-encoding, we just make a blob of all the
hpack-encoded headers first, and then we split that blob
in as many frames as necessary.

Support very large headers

---

src/fuzz_bridge.rs

The oss-fuzz build has been failing for a while and I noticed it was due to changes in the `encode` function. This fixes it

fuzzing: fix build

---

src/client.rs
src/codec/error.rs
src/codec/framed_read.rs
src/codec/mod.rs
src/error.rs
src/frame/go_away.rs
src/frame/reset.rs
src/hpack/encoder.rs
src/hpack/mod.rs
src/hpack/test/fuzz.rs
src/lib.rs
src/proto/connection.rs
src/proto/error.rs
src/proto/go_away.rs
src/proto/mod.rs
src/proto/peer.rs
src/proto/settings.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/streams.rs
src/server.rs
tests/h2-support/src/mock.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/codec_read.rs
tests/h2-tests/tests/flow_control.rs
tests/h2-tests/tests/push_promise.rs
tests/h2-tests/tests/stream_states.rs

h2::Error now knows whether protocol errors happened because the user
sent them, because it was received from the remote peer, or because
the library itself emitted an error because it detected a protocol
violation.
It also keeps track of whether it came from a RST_STREAM or GO_AWAY
frame, and in the case of the latter, it includes the additional
debug data if any.

Refactor errors (fixes #530)

---

src/error.rs
tests/h2-tests/tests/server.rs

The `Error::reason()` method regressed by not checking if the internal kind was a user-created error. The second commit fixes this. The first commit was adding a test about `send_reset`, which didn't actually end up being the problem, but we didn't have an explicit test, so included it anyways.
Fixes #561

Fix Error::reason regression

---

src/frame/headers.rs

I don't love that this doesn't include a test... But, the test is *exactly* the same as in https://github.com/hyperium/h2/pull/571, but just with the stream ID changed to 0. Seemed like a waste to include duplicate tests...

fix: properly reject prioritized HEADERS with stream ID of zero

---

src/client.rs
src/proto/connection.rs
src/proto/mod.rs
src/proto/streams/mod.rs
src/proto/streams/send.rs
src/server.rs
tests/h2-tests/tests/flow_control.rs

An alternative to #577.
This makes the max send buffer size **per stream**, instead of for the entire connection. It also does a lot less to try to enforce it, since the assigning of capacity is a complicated beast. All this does is clamp how high something like `SendStream::capacity()` will return. It's more just an advisory to the user of the `SendStream`.
Since hyper currently will only produce more data once the available capacity is over zero, it should behave well with this change. I've tried out this patch in the hyper HTTP/2 benchmarks, and see that they all still pass (don't hang). However, this is missing some unit tests in `flow_control.rs`...

Add max send buffer per stream option

---

tests/h2-support/Cargo.toml
tests/h2-support/src/trace.rs

This makes reading the logs way easier on the eyes.

Update tracing-subscriber and use tracing-tree when testing

---

src/proto/streams/recv.rs

We have reports of runtime panics (linkerd/linkerd2#7748) that sound a
lot like rust-lang/rust#86470. We don't have any evidence that these
panics originate in h2, but there is one use of `Instant::sub` that
could panic in this way.
Even though this is almost definitely a bug in Rust, it seems most
prudent to actively avoid the uses of `Instant` that are prone to this
bug. These fixes should ultimately be made in the standard library, but
this change lets us avoid this problem while we wait for those fixes.
This change replaces uses of `Instant::elapsed` and `Instant::sub` with
calls to `Instant::saturating_duration_since` to prevent this class of
panic.
See also hyperium/hyper#2746

Avoid time operations that can panic

---

Cargo.toml
README.md

The IETF only define HTTP/2 with no minor version. And at this stage I think its safe to assume that will never change.
Remaining references to HTTP/2.0 after this PR would be: one in the changelog, one in the GitHub repo About section. 
I avoided touching the changelog since it felt like rewriting history, but let me know if you feel different

HTTP/2 is the official name, so update terms

---

src/hpack/decoder.rs

Decoding error when processing continuation frames

Not to consume buf when decoding non_huff header name(which consumes the buf) succeeded but header value failed (DecoderError::NeedMore)

---

src/client.rs
src/server.rs

Currently, the `tracing` spans for the client and server handshakes
contain the name of the I/O type. In some cases, where nested I/O types
are in use, these names can be quite long; for example, in Linkerd, we
see log lines like this:
```
2022-03-07T23:38:15.322506670Z [ 10533.916262s] DEBUG ThreadId(01) inbound:accept{client.addr=192.168.1.9:1227}:server{port=4143}:direct:gateway{dst=server.echo.svc.cluster.local:8080}:server_handshake{io=hyper::common::io::rewind::Rewind<linkerd_io::either::EitherIo<linkerd_io::sensor::SensorIo<linkerd_io::prefixed::PrefixedIo<linkerd_io::either::EitherIo<tokio_rustls::server::TlsStream<linkerd_io::either::EitherIo<linkerd_io::scoped::ScopedIo<tokio::net::tcp::stream::TcpStream>, linkerd_io::prefixed::PrefixedIo<linkerd_io::scoped::ScopedIo<tokio::net:: …
```

tracing: remove I/O type names from handshake spans

---

src/frame/mod.rs

Nightly has begun running doctests for unexported macros as of
https://github.com/rust-lang/rust/pull/96630, which caused a doctest for
test_unpack_octets_4 which was previously ignored to be run. This broke
the CI because macros that are not exported with `#[macro_export]`
cannot be used from external crates (and thus cannot be doctested). This
change ignores the doctest and copies the relevant code into a unit
test.

Move unexported macro doctest into unit test

---

src/error.rs

We are trying to determine if the remote issued a stream reset and found that this test is missing from the `Status` type.
Closes #617

Add `Status::is_reset` function

---

src/client.rs
src/server.rs

Signed-off-by: Ryan Russell <git@ryanrussell.org>

Fix Typo `received`

---

src/proto/streams/streams.rs
tests/h2-tests/tests/server.rs

Http2 Server are allowed to early respond without fully
consuming client input stream, but must respond with an
error code of NO_ERROR when sending RST_STREAM.
Nginx treat any other error code as fatal if not done so
Commit change error code from CANCEL to NO_ERROR, when the
server is early responding to the client
https://github.com/hyperium/h2/issues/633
https://trac.nginx.org/nginx/ticket/2376

Use RST_STREAM(NO_ERROR) in case server early respond (#633)

---

src/client.rs

Remove redundant and misleading phrase in client::Builder::enable_push documentation.
Resolves #645
r? @seanmonstar

Fix docs of enable_push

---

src/proto/streams/recv.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs

fix issue#648: drop frame if stream is released

---

src/client.rs
src/proto/streams/streams.rs
src/server.rs
tests/h2-support/src/client_ext.rs
tests/h2-support/src/prelude.rs

When proxying large requests, I want to be able to pass the request body straight through my server without loading all of it it in memory at once. This is currently very difficult due to the (seemingly) arbitrary `'static` bound on Hyper's body generic. And so, I want to remove the `'static` bounds for hyper 1.0, but before I can do that I need to remove them from here. (Will this require an h2 release before I can make the hyper patch?)
- Removed unnecessary bounds from body generic
- ~~Fixed all clippy warnings~~ (Moved to #652)

Removed unnecessary `'static` & Unpin bounds from body generic

---

src/server.rs

Without this, logs just show things like `h2::server: :scheme in CONNECT`; this is not super useful unless I already happened to know that is invalid. With this, it will indicate it is malformed explicitly, like other usages in the file.

Consistently indicate `malformed` in logs

---

src/server.rs
tests/h2-tests/tests/server.rs

This exposes the :protocol pseudo header as Request extension.
Fixes #347

Add Protocol extension to Request on Extended CONNECT

---

src/proto/streams/flow_control.rs
src/proto/streams/prioritize.rs

We met the panic in our production environment, so handle this panic
condition before panic. stack backtrace:
0: rust_begin_unwind
at
/rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
1: core::panicking::panic_fmt
at
/rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
2: core::panicking::panic
at
/rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
3: h2::proto::streams::flow_control::FlowControl::send_data
at
/build/vendor/h2/src/proto/streams/flow_control.rs:176:9
4: h2::proto::streams::prioritize::Prioritize::pop_frame::{{closure}}
at
/build/vendor/h2/src/proto/streams/prioritize.rs:737:33
5: tracing::span::Span::in_scope
at /build/vendor/tracing/src/span.rs:982:9
6: …

fix: panic in pop_frame()

---

src/proto/streams/prioritize.rs
src/proto/streams/send.rs
src/proto/streams/stream.rs
tests/h2-tests/tests/flow_control.rs

Fixes #628
Sometimes `poll_capacity` returns `Ready(Some(0))` - in which case
caller will have no way to wait for the stream capacity to become available.
The previous attempt on the fix has addressed only a part of the problem.
The root cause - in a nutshell - is the race condition between the
application tasks that performs stream I/O and the task that serves
the underlying HTTP/2 connection. The application thread that is about
to send data calls `reserve_capacity/poll_capacity`, is provided
with some send capacity and proceeds to `send_data`.
Meanwhile the service thread may send some buffered data and/or
receive some window updates - either way the stream's effective
allocated send capacity may not change, but, since the capacity still
available, `send_capacity_inc` flag may be set. …

Avoid spurious wakeups when stream capacity is not available

---

src/proto/streams/state.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/client_request.rs

It's quite confusing from production logs when all I get is "broken pipe" and I don't know which path was taken for that error to be logged.

Add a message for EOF-related broken pipe errors

---

src/client.rs
src/proto/connection.rs
src/proto/mod.rs
src/proto/streams/counts.rs
src/proto/streams/mod.rs
src/proto/streams/recv.rs
src/proto/streams/state.rs
src/proto/streams/streams.rs
src/server.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/stream_states.rs

Streams that have been received by the peer, but not accepted by the user, can also receive a RST_STREAM. This is a legitimate pattern: one could send a request and then shortly after, realize it is not needed, sending a CANCEL.
However, since those streams are now "closed", they don't count towards the max concurrent streams. So, they will sit in the accept queue, using memory.
In most cases, the user is calling `accept` in a loop, and they can accept requests that have been reset fast enough that this isn't an issue in practice.
But if the peer is able to flood the network faster than the server accept loop can run (simply accepting, not processing requests; that tends to happen in a separate task), the memory could grow.
So, this introduces a maximum count for streams in the …

fix: limit the amount of pending-accept reset streams

---

src/frame/go_away.rs
src/proto/connection.rs
src/proto/go_away.rs
src/server.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/server.rs

Fixes hyperium/hyper#3200
Debug data in GOAWAY frames is opaque information meant for diagnostic purposes. The data was previously read and stored when being received, but was never written during encoding.
This pull request includes the data when encoding the frame but does not add a (stable) way of setting the data. If it is desired I am happy to include it too. I suspect the function added for testing purposes wouldn't be fit for a stable, public API.
Additionally, I've included an integration test as described in the original issue. However, I'm quite sure there is a better way of creating the GOAWAY frame, I'm just not familiar enough with the structure of the integration tests to find it at the moment. With a few pointers I'd like to rewrite how it is done, if needed.

#3000: Serialize debug_data when present in GOAWAY frames

---

src/frame/go_away.rs
src/proto/connection.rs
src/proto/error.rs
src/proto/streams/recv.rs
src/server.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/server.rs
tests/h2-tests/tests/stream_states.rs

Fixes hyperium/hyper#3211
Figured I'd pick this issue up too. This PR one is pretty straight forward and I have no real concerns or sore points. Happy to make changes as needed.

Add too_many_resets debug_data to the GOAWAY we send

---

src/proto/streams/recv.rs
tests/h2-tests/tests/stream_states.rs

I noticed in logs that when a stream was dropped, and thus within `transition` and ready to expire as a locally reset stream, it would then pop its related push promises, and _those_ could trigger the original stream to call `transition_after`. The end result is that the original stream would call `dec_num_reset_streams()` twice.
This gets rid of a dangerous call to `transition_after` that is happening outside the bounds of a transition. It ends up making _newer_ streams that are locally reset to get forgotten, instead of older streams, but that's not really better or worse.
There is a fuzz seed that triggered the panic, and with this change, that fuzz seed no longer panics.

fix: panicked when a reset stream would decrement twice

---

src/proto/streams/recv.rs
src/proto/streams/streams.rs
src/server.rs
tests/h2-tests/Cargo.toml
tests/h2-tests/tests/server.rs

Sending a response frame to an `h2` server triggers a panic. this PR makes the `take_request` function return a Result instead of panicking.

h2 server panics when receiving headers that look like response

---

src/proto/streams/recv.rs
src/proto/streams/streams.rs
src/server.rs
tests/h2-tests/tests/server.rs

Corrected fix in #690 - the root cause was that informational header frames are ignored, even if received by the server. However, the stream was still scheduled in `pending_accept`. This then triggers the `take_request`, while nothing is put in the `pending_recv` queue, which then causes the panic.

Fix for invalid header panic corrected

---

src/proto/connection.rs
src/proto/mod.rs
src/proto/streams/flow_control.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/flow_control.rs

Fuzzing discovered a integer underflow in the flow control handling that can be triggered by a certain sequence of frames. In release builds this would lead to wrap-around of the negative window. This seems incorrect to me. I did not find anything definitive in the http2 spec.
Removed the SubAssign, etc. syntactic sugar functions and switched to return Result on over/underflow
Whenever possible, switched to returning a library GoAway protocol error. Otherwise we check for over/underflow only with `debug_assert!`, assuming that those code paths do not over/underflow. In this case I left `TODO:` comments.

Fix for a fuzzer-discovered integer underflow of the flow control window size

---

tests/h2-tests/tests/server.rs

- fix of the test's name after changing it in #634
- additional test that server also sends data frames correctly
This is normal scenario and I decided to extend test a bit.

test: early server response with data

---

.github/workflows/CI.yml

Updates to `actions/checkout@v4` from version 3.

chore(ci): update to actions/checkout@v4

---

.github/workflows/CI.yml
Cargo.toml
tests/h2-support/Cargo.toml

This pull request contains some changes related to the minimal version checking.
- Brings back a minimal versions checking in ci, changed to be run on stable Rust.
- Marks `h2-support` as a private crate not to affect minimal versions.
- Fixes `tracing` minimal version, which seems to have been affected by `h2-support`.

chore(dependencies): update tracing minimal version to 0.1.35

---

src/client.rs
src/codec/framed_read.rs
src/codec/mod.rs
src/frame/settings.rs
src/proto/settings.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/client_request.rs

The function's description may need some refinement
Closes #637

Add a setter for `header_table_size`

---

src/error.rs
src/proto/streams/prioritize.rs
tests/h2-tests/tests/prioritization.rs

Fixes https://github.com/hyperium/hyper/issues/3338
This PR changes the the assign-capacity queue to prioritize streams that are send-ready.
This is necessary to prevent a lockout when streams aren't able to proceed while waiting for connection capacity, but there is none.

fix: streams awaiting capacity lockout

---

src/client.rs
src/proto/settings.rs
src/proto/streams/counts.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/client_request.rs

Currently, if the server provides no value as `MAX_CONCURRENT_STREAMS` in its initial `SETTINGS` frame, the client keeps using the value set by [`h2::client::Builder::initial_max_send_streams`]. However, given that the absence of `MAX_CONCURRENT_STREAMS` in the initial `SETTINGS` frame implies that the server is willing to accept unlimited number of concurrent streams, it is more reasonable to overwrite the value set by [`h2::client::Builder::initial_max_send_streams`] with `usize::MAX` in this case.
Note that this overwrite only happens when the server does not advertise `MAX_CONCURRENT_STREAMS` in its _initial_ `SETTINGS` frame. For second and later `SETTINGS` frames that do not include `MAX_CONCURRENT_STREAMS`, the client will not update the value and keep using the previously …

fix: set `MAX_CONCURRENT_STREAMS` to `usize::MAX` if no value is advertised initially

---

src/client.rs
src/proto/connection.rs
src/proto/mod.rs
src/proto/streams/counts.rs
src/proto/streams/mod.rs
src/proto/streams/streams.rs
src/server.rs

This change causes GOAWAYs to be issued to misbehaving connections which for one reason or another cause us to emit lots of error resets.
Error resets are not generally expected from valid implementations anyways.
The threshold after which we issue GOAWAYs is tunable, and will default to 1024.

streams: limit error resets for misbehaving connections

---

src/proto/connection.rs
src/proto/streams/buffer.rs
src/proto/streams/streams.rs
tests/h2-support/src/mock.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/server.rs

closes https://github.com/hyperium/hyper/issues/3427
This PR makes it so that if we encountered `UnexpectedEof` as a server, and when there is nothing else to send (i.e. we sent what the client wanted), `Connection::poll` will not return an `Err`.
Note that this does not change the client behaviour when the server closed the connection abruptly.
---
Something to consider is whether we should handle this in hyper instead. But I don't see a good reason why we shouldn't put it in `h2`

feat: not returning UnexpectedEof when client drop without close_notify

---

.github/workflows/CI.yml
src/frame/headers.rs
src/proto/streams/store.rs

This speeds up loading blocks in cases where we have many headers already.

perf: optimize header list size calculations

---

Cargo.toml
examples/akamai.rs
src/frame/headers.rs

msrv is already newer than `2021`. However `2021` also enables the v2 resolver

set rust `edition` to `2021`

---

src/frame/headers.rs
src/proto/streams/store.rs

This speeds up loading blocks in cases where we have many headers already.

cherry pick 750: optimize header list size calculations

---

src/codec/framed_read.rs
tests/h2-tests/tests/server.rs

Calculate the amount of allowed CONTINUATION frames based on other settings.
max_header_list_size / max_frame_size
That is about how many CONTINUATION frames would be needed to send headers up to the max allowed size. We then multiply by that by a small amount, to allow for implementations that don't perfectly pack into the minimum frames *needed*.
In practice, *much* more than that would be a very inefficient peer, or a peer trying to waste resources.
See https://seanmonstar.com/blog/hyper-http2-continuation-flood/ for more info.

backport 0.3.x - fix: limit number of CONTINUATION frames allowed

---

Cargo.toml
benches/main.rs

This PR adds a simple benchmark to measure perf improvement changes. E.g., a potential fix for this issue: https://github.com/hyperium/h2/issues/531
The benchmark is simple: have a client send `100_000` requests to a server and wait for a response. 
Output:
```
cargo bench
H2 running in current-thread runtime at 127.0.0.1:5928:
Overall: 353ms.
Fastest: 91ms
Slowest: 315ms
Avg    : 249ms
H2 running in multi-thread runtime at 127.0.0.1:5929:
Overall: 533ms.
Fastest: 88ms
Slowest: 511ms
Avg    : 456ms
```

Add a simple benchmark

---

CONTRIBUTING.md

Gitter chat has notification that community discussion were moved to Discord.
Link to community discussion updated to point directly to Discord.

Add link to Tokio Discord.

---

src/client.rs
src/proto/connection.rs

See https://github.com/hyperium/hyper/issues/3652.
What I have found is the final reference to a stream being dropped after the `maybe_close_connection_if_no_streams` but before the `inner.poll()` completes can lead to the connection dangling forever without any forward progress. No streams/references are alive, but the connection is not complete and never wakes up again. This seems like a classic TOCTOU race condition.
In this fix, I check again at the end of poll and if this state is detected, wake up the task again.
Wth the test in https://github.com/hyperium/hyper/pull/3655, on my machine, it fails about 5% of the time:
```
1876 runs so far, 100 failures (94.94% pass rate). 95.197349ms avg, 1.097347435s max, 5.398457ms min
```
With that PR, this test is 100% reliable
```
64010 runs so …
```

Fix race condition in connection termination

---

src/frame/headers.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/server.rs

`CONNECT` & `OPTIONS` request has special requirements regarding :path & :scheme pseudo-header which were not met.
Construction of pseudo-header was fixed to not include `:path` & `:scheme` fields for `CONNECT` method. Empty `:path` field for `OPTIONS` requests now translates to `'*'` value sent in `:path` field.
`CONNECT` request changes were tested against server based on hyper 1.2.

#769: Fix request pseudo-header construction for CONNECT & OPTION methods

---

Cargo.toml
src/client.rs
src/lib.rs
src/proto/ping_pong.rs
src/server.rs
src/share.rs

This removes ones of the heavier dependencies. The goal is to also remove
futures-util from the rest of the dependency tree, which is hard to justify when
futures-util is used in more fundamental dependencies.
Closes #507 
Signed-off-by: John Nunley <dev@notgull.net>

Replace futures-util with atomic-waker and manual poll_fn

---

src/client.rs
src/proto/streams/streams.rs

Addresses https://github.com/hyperium/hyper/issues/3623
This PR exposes the max count of recv and send streams for h2.

feat: expose current max {recv,send} stream count

---

.github/workflows/CI.yml

Uses tokio 1.38.1 in the MSRV checking as tokio 1.39 bumps its MSRV to 1.70.

chore(ci): use tokio 1.38.1 in MSRV check

---

.github/workflows/CI.yml
Cargo.toml
src/lib.rs

Uses `lints.rust.unexpected_cfgs` in the manifest.

chore: use lints.rust.unexpected_cfgs in manifest

---

src/frame/headers.rs

Flattens unnecessary nested if expression.

chore: flatten unnecessary nested if expression

---

src/lib.rs
src/share.rs

Add indents to the newline of list.

chore(doc): add indent to newline of list

---

src/client.rs
src/frame/stream_id.rs
src/hpack/table.rs
src/proto/streams/counts.rs
src/proto/streams/stream.rs
src/server.rs

Replaces legacy numeric constants with corresponding one.

chore: replace legacy numeric constant with corresponding one

---

src/hpack/encoder.rs
src/hpack/test/fixture.rs

Removes unnecessary type converting.

chore: remove unnecessary type converting

---

src/proto/streams/send.rs
tests/h2-tests/tests/client_request.rs

Before this change, the transition to the reset state wouldn't notify tasks that were waiting for a response. The motivating case for this patch involved a large header being sent by the server. This case was mostly tested by an existing test, but because that test did not spawn separate tasks and kept polling the futures through its use of `conn.drive`, the missing notify was masked.
Informs https://github.com/hyperium/hyper/issues/3724.

streams: notify recv task upon reset

---

src/proto/streams/recv.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/push_promise.rs
tests/h2-tests/tests/server.rs

Noticed during #791 
cc @ajwerner

fix: send PROTOCOL_ERROR instead of REFUSED_STREAM for oversized headers

---

src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/push_promise.rs

The push task is a separate task from the recv task, so its state needs to be tracked separately for waking. I don't know how to be systematic about ensuring that notify_push is called in all the right places, but this is an initial attempt.
In order to test this works, we manually utilize FuturesUnordered which does fine-grained task wake tracking. The added test failed before making the other changes.

streams: PushPromises tasks are notified correctly

---

tests/h2-support/src/future_ext.rs
tests/h2-support/src/prelude.rs
tests/h2-tests/tests/client_request.rs
tests/h2-tests/tests/codec_read.rs
tests/h2-tests/tests/codec_write.rs
tests/h2-tests/tests/flow_control.rs
tests/h2-tests/tests/ping_pong.rs
tests/h2-tests/tests/prioritization.rs
tests/h2-tests/tests/push_promise.rs
tests/h2-tests/tests/server.rs
tests/h2-tests/tests/stream_states.rs

This commit adds wrappers around futures::future helpers and augments
TestFuture to ensure that the underlying futures are notified before
they are polled. This helps to catch bugs where there are missing notify
calls or bad handling of the waker.
The commit then extends the tests to use these helpers instead of the
library functions from futures.
It also ammends the client_requests::recv_too_big_headers test to no
longer use the tokio spawned tasks that were added in https://github.com/hyperium/h2/pull/791.

h2-support,h2-tests: add tools to ensure wake 

---

src/codec/framed_read.rs
src/frame/headers.rs
src/frame/util.rs

This removes `let _ = ` from in front of `split_to` and `split_off` and mostly follows the suggestions from the `#[must_use]` impls. One of the uses of `split_to` is instead replaced with `take`.

style: replace `split_to` and `split_off` with better alternatives

---

src/frame/headers.rs
src/proto/streams/recv.rs
tests/h2-tests/tests/client_request.rs

Before this change, content-length underflow is only checked when receiving date frames.
This change adds similar check for headers frames.

Header frame with non-zero content-length and END_STREAM is malformed

---

src/proto/streams/streams.rs

Detected during an extension of the `useless_conversion` Clippy lint.

chore: remove unnecessary type conversion

---

tests/h2-tests/tests/flow_control.rs

This helps finding the root cause of why the assertion in FlowControl::dec_send_window failed in the first place.
See #692 for more details.

Simplify window_size_decremented_past_zero

---

src/proto/streams/prioritize.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/flow_control.rs

Reclaiming requested capacity that has not been actually reserved yet is wrong, as this capacity never existed to begin with.

Fix reclaiming reserved capacity (fixes #607)

---

src/client.rs

When in a slow shutdown, this was busy looping since no more streams were left. The change here now only makes sure we poll one extra time if the state changed during the poll.
Fixes #831

fix: busy loop on shutdown

---

src/proto/streams/send.rs
tests/h2-tests/tests/flow_control.rs

Send-closed streams should be skipped when decreasing window size, as they are skipped when increasing it.

Fix window size decrement of send-closed streams

---

src/proto/streams/counts.rs
src/proto/streams/prioritize.rs
tests/h2-tests/tests/stream_states.rs

A stream whose ref count reaches zero while open should not immediately decrease the number of active streams, otherwise MAX_CONCURRENT_STREAMS isn't respected anymore.

Handle implicit resets at the right time

---

src/codec/framed_write.rs

Fix `poll_flush` after `poll_shutdown`

---

src/proto/connection.rs
src/server.rs

Expose "streams check" to support keepalive timeout in external project.
We have test the idea in our project and found it success.
maybe solve issue #826

Try to support Keepalive Timeout, expose 'streams check' for `Connection`

---

.github/workflows/CI.yml

This just pins our CI to the latest working version of `once_cell`.

chore: Fix msrv ci build

---

src/proto/streams/stream.rs

This implements a custom `Debug` impl for `Stream` so that the `Waker` type stored in the `*_task` fields does not get printed. This is because the `Debug` impl of `Waker` prints a pointer which is non-deterministic. My use-case here is that I am trying to make turmoil deterministic and testing it with h2 via comparing trace logs between two same seeded runs.

fix: `Stream` debug impl to not print `Waker`

---

src/proto/streams/recv.rs
src/proto/streams/state.rs
tests/h2-tests/tests/flow_control.rs

Before this change, it returned true on other types of disconnection as well.
Fixes #806
Removed unused `is_recv_closed()`.

Fix RecvStream::is_end_stream(): return true only when END_STREAM is received

---

src/proto/connection.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/client_request.rs

This PR extends the change made in #743 to include client connections that are closed by servers that drop connections without sending `close_notify` when the client has nothing to send.
This is motivated by server H2 implementations  sending `go_away` frames and then closing the connections without a `close_notify` in longer lived applications (specifically DoH).
I originally reported this as an issue in the `hickory-dns` (https://github.com/hickory-dns/hickory-dns/issues/3064) but after discussion with @djc the real underlying issue seems to be the handling of this type of intentional connections close within the H2 client.

feat: not return UnexpectedEof when server drops without close_notify

---

src/client.rs
src/proto/mod.rs
src/proto/streams/recv.rs
src/server.rs

h2 has mechanisms to remember a local reset stream for some time afterward, to support what it says in RFC 9113 SS 5.4.2:
> A RST_STREAM is the last frame that an endpoint can send on a stream. The peer that sends the RST_STREAM frame MUST be prepared to receive any frames that were sent or enqueued for sending by the remote peer. These frames can be ignored, except where they modify connection state (such as the state maintained for field section compression (Section 4.3) or flow control).
>
> Normally, an endpoint SHOULD NOT send more than one RST_STREAM frame for any stream. However, an endpoint MAY send additional RST_STREAM frames if it receives frames on a closed stream after more than a round-trip time. This behavior is permitted to deal with misbehaving implementations.
We don't …

fix: adjust expiring reset stream limits
