hyperium/h2

examples/client.rs
examples/server-tr.rs
src/client.rs
src/frame/headers.rs
src/lib.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/streams.rs
src/server.rs
tests/support/mod.rs
tests/trailers.rs

Missing tests (and actually verifying that this works).

Wire in trailers

---

src/client.rs

I've rewritten the client handshake to store the inner future with a named type, rather than as a `Box<Future>`. This also means that the `'static` lifetime bounds on the type parameters `T` and `B` can be removed.
I've ran the tests against this branch and everything passes. Since no new functionality was added, I haven't added any additional tests.
Potential drawbacks of this change are hat it does make some code in `client.rs` a bit more complex, and that the type of the inner future in `Handshake` may need to be updated if certain aspects of the implementation of `Client::handshake2` are changed. However, there isn't currently any other way to remove the `Box` in this situation.

Unbox client handshake future

---

src/client.rs
src/frame/ping.rs
tests/client_request.rs
tests/codec_read.rs
tests/flow_control.rs
tests/ping_pong.rs
tests/prioritization.rs
tests/server.rs
tests/stream_states.rs
tests/support/src/assert.rs
tests/support/src/codec.rs
tests/support/src/future_ext.rs
tests/support/src/lib.rs
tests/support/src/mock.rs
tests/support/src/prelude.rs
tests/support/src/raw.rs
tests/trailers.rs

Writing raw H2 byte exchanges is annoying. Let's add some infrastructure for working with frames at the very least.

Add test infrastructure to work directly with frames

---

src/frame/mod.rs
src/frame/ping.rs
src/frame/settings.rs
src/proto/connection.rs
src/proto/mod.rs
src/proto/streams/prioritize.rs
tests/prioritization.rs
tests/support/src/assert.rs
tests/support/src/prelude.rs

Fixes a bug in the prioritization layer. The counter of buffered data per stream was never decremented.
Fixes #60.

Fix bug in prioritization

---

src/proto/streams/prioritize.rs
tests/flow_control.rs

The requested capacity was not decreased as data is written.

Flow control bug fix

---

src/proto/streams/recv.rs
tests/flow_control.rs

Fixes https://github.com/carllerche/h2/issues/65

increment stream window capacity when sending window update

---

Cargo.toml
src/client.rs
src/lib.rs
src/proto/connection.rs
src/proto/peer.rs
src/proto/streams/counts.rs
src/proto/streams/mod.rs
src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/store.rs
src/proto/streams/stream.rs
src/proto/streams/streams.rs
tests/stream_states.rs
tests/support/src/future_ext.rs

**Work in progress**
Try to actually free memory...

Ref count stream state and release when final.

---

src/proto/streams/streams.rs

This is a pretty minor change, but I was working on #75 & noticed the TODO comment. I extracted the code for resetting a stream on `RecvError::Stream` & moved it to a function on `Actions`.
Notes:
+ I briefly considered making the function on `store::Ptr`(so it could be invoked as `stream.reset_on_recv_stream_err(actions, result)`, which seems somewhat more semantically correct, but putting the function on `Ptr` didn't seem to be as good a separation of concerns.
+ Method name feels too long, but I couldn't come up with a shorter one that was descriptive of what the method does...

Factor out reset on RecvError::Stream

---

src/codec/framed_read.rs
src/proto/streams/prioritize.rs
tests/flow_control.rs
tests/prioritization.rs
tests/support/src/lib.rs
tests/support/src/mock.rs
tests/support/src/prelude.rs
tests/support/src/util.rs

Fix send flow control bug

---

src/codec/framed_read.rs
src/codec/mod.rs

remove unstable for Codec methods used internally

---

src/client.rs
src/proto/connection.rs
src/proto/streams/send.rs
src/proto/streams/streams.rs
tests/client_request.rs

Client::poll_ready() returns an Error if next stream ID would overflow

---

src/proto/streams/recv.rs
src/proto/streams/state.rs
tests/flow_control.rs
tests/server.rs
tests/support/mock.rs

Fixes #110 
Adds a simple server test.

Fix stream-id double-accounting bug

---

src/client.rs

add send_reset to client::Stream

---

src/codec/error.rs
src/error.rs
src/proto/error.rs
src/proto/streams/recv.rs
src/proto/streams/streams.rs
tests/client_request.rs

Client::poll_ready and send_request may return Connection Errors

---

src/client.rs
src/codec/framed_read.rs
src/frame/reason.rs
src/proto/connection.rs
src/proto/streams/flow_control.rs
src/proto/streams/mod.rs
src/proto/streams/recv.rs
src/proto/streams/send.rs
src/proto/streams/state.rs
src/proto/streams/streams.rs
src/server.rs
tests/support/frames.rs

Addresses issue #128.
(First pull request to the project. If there's anything I can change about flow or provided info, or to better comply with CONTRIBUTING, please let me know).

Issue 128: Convert frame::Reason to struct

---

.travis.yml
tests/flow_control.rs
tests/support/prelude.rs

Code coverage is causing the build to hang. This also fixes a race in a test.
See #156

Disable CI code coverage checks

---

README.md

Add FAQ section to readme

---

tests/stream_states.rs

As requested in https://github.com/carllerche/h2/issues/38#issuecomment-328254128, I've added a test to `stream_states.rs` to cover the case where we receive a HEADERS frame that gets rejected (due to being malformed), then the same stream ID is received with a valid HEADERS frame which gets accepted.

Add test that recv.next_stream_id should be updated in `open`

---

src/hpack/decoder.rs

This updates `peek_u8` in hpack decoder to internally perform bound
checking. This ensures it cannot access bytes out of range once
reaching the end of the buffer.
Fixes: https://github.com/carllerche/h2/issues/19

hpack/decoder: add bound check to peek_u8

---

src/client.rs
src/lib.rs
src/server.rs
src/share.rs

A lot more docs are needed. This focuses mostly on the server module.

Start writing API docs

---

src/proto/streams/recv.rs
src/proto/streams/streams.rs
tests/flow_control.rs

release connection capacity when recv_data has stream error

---

src/server.rs
src/share.rs

This includes a section on inbound data control flow.

Add more library API documentation

---

src/proto/streams/streams.rs
tests/stream_states.rs

ignore trailers for some time on locally reset streams

---

src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/state.rs
tests/stream_states.rs

add test that a window update can be received in reserved state

---

src/proto/streams/prioritize.rs
src/proto/streams/recv.rs
src/proto/streams/streams.rs
tests/push_promise.rs

reset pending push promises if user drops all refs

---

src/frame/data.rs

The only caller already guards against the case.
Relates to #192

Switch unimplemented to assert

---

src/proto/streams/prioritize.rs
src/proto/streams/send.rs
src/proto/streams/stream.rs
tests/server.rs

send reset CANCEL when SendStream is dropped with no end-of-stream sent

---

src/hpack/decoder.rs

The spec specifically allows accepting HPACK literals with indexing when
the HPACK literal is greater than the max table size. In this case, the
literal is not inserted in the table.
Fixes #243

Accept HPACK literals greater than max size

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Bump version to v0.1.5

---

tests/h2-tests/tests/client_request.rs

There was a race condition in the test where the server connection
sometimes closed before the final client opereation. This triggered an
unwrap in the test.
This patch updates the test to ensuree that the mock server connection
stays open until the client test is complete.

Fix spurrious test failure

---

Cargo.toml

Unpacked: 59M
Compressed: 5.4M
Unpacked: 788K
Compressed: 133K

Do not distribute the test fixtures in published crates

---

src/proto/streams/send.rs
tests/h2-tests/tests/flow_control.rs

From my understanding of the code and the HTTP/2 spec, we shouldn't try to reclaim `dec` from the `available` flow, but rather only take away any excess if it would exceed the new `window_size`.
This fixes a deadlock we observed: if we manage to send out a a new stream's HEADERS frame just before receiving a SETTINGS frame from the server that decreases the initial window size, `available` would be dropped down to zero and never requeued, causing us to never send `DATA` and then eventually time out. This is probably easy enough to write a test for but I don't have the time for it at the moment.

Fix the handling of incoming SETTINGS_INITIAL_WINDOW_SIZE.

---

src/proto/streams/prioritize.rs
tests/h2-tests/tests/flow_control.rs

fix panic when calling reserve_capacity after connection closes

---

src/proto/streams/send.rs

Fix the initial send window size.

---

src/proto/connection.rs

This will in particular send close notify alerts for TLS streams.

Shutdown the stream along with connection

---

src/proto/streams/streams.rs

Add OpaqueStreamRef constructor

---

tests/h2-fuzz/src/main.rs

This is how I found #319 and #320.

Augment h2-fuzz to open multiple concurrent streams.

---

src/frame/data.rs
src/frame/util.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/codec_read.rs
tests/h2-tests/tests/flow_control.rs

Originally reported in https://github.com/hyperium/hyper/issues/1697

fix inverted split for DATA frame padding

---

src/proto/streams/recv.rs
src/proto/streams/streams.rs
tests/h2-tests/tests/flow_control.rs

Previously, any streams that were dropped or closed while not having
consumed the inflight received window capacity would simply leak that
capacity for the connection. This could easily happen if a `RecvStream`
were dropped before fully consuming the data, and therefore a user would
have no idea how much capacity to release in the first place. This
resulted in stalled connections that would never have capacity again.

Release closed streams capacity back to connection

---

src/proto/connection.rs
src/proto/go_away.rs
src/server.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/server.rs

Prevent server Connection from returning same error after calling abrupt shutdown

---

src/proto/streams/store.rs

- Removes incrementing counter, instead just using the StreamId as a
slab ABA guard.
- Adjusts Ptr::deref to use Store::index, as before it was skipping to
check the ABA guard.
- Rename fields and types to clarify it actually is an ABA guard.
- Improve panic message in case a dangling Ptr is accessed.

Refactor proto::streams::store indices

---

src/proto/streams/recv.rs
src/proto/streams/streams.rs
src/share.rs

Clear recv buffer when stream refs are dropped

---

src/client.rs
src/codec/framed_read.rs
src/codec/framed_write.rs
src/codec/mod.rs
src/frame/settings.rs
src/hpack/decoder.rs
src/hpack/encoder.rs
src/hpack/test/fuzz.rs
src/proto/settings.rs
src/server.rs
tests/h2-support/src/frames.rs
tests/h2-support/src/mock.rs
tests/h2-tests/tests/codec_read.rs
tests/h2-tests/tests/stream_states.rs

Ref: https://github.com/linkerd/linkerd2/issues/3141

Fix support for SETTING_HEADER_TABLE_SIZE

---

README.md

Hi, developers! Thank you for your great project.
I think HTTPS is better for everyone.

Use https for H2 Database link

---

Cargo.toml
tests/h2-fuzz/Cargo.toml
tests/h2-support/Cargo.toml
tests/h2-tests/Cargo.toml

Update tokio alpha.6

---

src/client.rs
src/lib.rs
src/proto/streams/flow_control.rs
src/proto/streams/streams.rs
src/server.rs
src/share.rs
tests/h2-tests/tests/flow_control.rs

- Adds `FlowControl::available_capacity` method.
- Adds `FlowControl::used_capacity` method.

Change `ReserveCapacity` to expanded `FlowControl` type

---

Cargo.toml
src/frame/headers.rs
src/server.rs
tests/h2-fuzz/Cargo.toml
tests/h2-support/Cargo.toml
tests/h2-tests/tests/client_request.rs

Update to http 0.2

---

src/proto/streams/store.rs

A connection can never have more than u32::MAX >> 1 streams, so we'll
never store more than that many in the store slab. Define the
`SlabIndex` as a `u32` to reduce the number of bytes moved around.

Use a u32 index for stream store

---

src/codec/framed_write.rs
src/codec/mod.rs
src/frame/settings.rs
src/hpack/encoder.rs
src/proto/settings.rs
tests/h2-support/src/prelude.rs
tests/h2-tests/tests/codec_write.rs

Respect SETTINGS_HEADER_TABLE_SIZE

---

src/server.rs

This is to follow up issue #466 .

fix documentation for server::Connection

---

tests/h2-fuzz/Cargo.toml

import futures with FuturesUnordered

fix h2-fuzz testing

---

src/codec/error.rs
src/frame/settings.rs
src/proto/connection.rs
src/proto/streams/send.rs
tests/h2-support/src/frames.rs
tests/h2-tests/tests/server.rs

Handle client-disabled server push

---

.github/workflows/CI.yml
Cargo.toml
examples/server.rs
src/codec/framed_write.rs
src/server.rs
tests/h2-fuzz/Cargo.toml
tests/h2-support/Cargo.toml
tests/h2-support/src/mock.rs
tests/h2-tests/Cargo.toml
tests/h2-tests/tests/codec_read.rs
tests/h2-tests/tests/flow_control.rs
tests/h2-tests/tests/hammer.rs

akamai example needs https://github.com/tokio-rs/tls/pull/29

update to tokio 0.3

---

Cargo.toml
src/codec/framed_write.rs
src/frame/headers.rs
src/hpack/encoder.rs
src/hpack/test/fixture.rs
src/hpack/test/fuzz.rs
src/proto/streams/prioritize.rs
tests/h2-fuzz/Cargo.toml
tests/h2-support/Cargo.toml
tests/h2-support/src/prelude.rs
tests/h2-tests/Cargo.toml

Upgrade to bytes 0.6

---

src/codec/framed_read.rs

This is exactly #484, but with the couple of review comments addressed.

de-generify FramedRead::decode_frame

---

src/proto/streams/prioritize.rs
src/proto/streams/stream.rs
tests/h2-tests/tests/flow_control.rs

Fix poll_capacity to wake in combination with max_send_buffer_size

---

src/frame/headers.rs

Fix panic when receiving malformed push promise with stream id 0

---

.github/workflows/CI.yml

Bump MSRV to 1.56

---

src/error.rs

feat: add Error::is_library method

---

src/proto/streams/state.rs
tests/h2-tests/tests/server.rs
tests/h2-tests/tests/stream_states.rs

fix: pending-accept remotely-reset streams pattern was checking is_local

---

.github/workflows/CI.yml
Cargo.toml

Checks minimal versions more precisely and fixes the detected tracing crate version.

Check minimal versions more precisely

---

CHANGELOG.md
Cargo.toml
src/lib.rs

Get the last things out before bumping to 0.4.

Prepare v0.3.22

---

src/error.rs
src/proto/streams/prioritize.rs
tests/h2-tests/tests/prioritization.rs

Cherry-picks #730 from master.

cherry-pick fix: streams awaiting capacity lockout (#730)

---

.github/workflows/CI.yml

ci: pin hashbrown for msrv job

---

.github/workflows/CI.yml
src/hpack/header.rs
src/proto/streams/store.rs
src/proto/streams/streams.rs

The compiler has started to complain about this, so fixing it up.

style: fix anonymous lifetime syntax

---

Cargo.toml

chore: update to webpki-roots 1
